######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 27 17:55:20 2011
######################################################################

TEMPLATE = lib
TARGET = qtkeychain
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += keychain.h \
    keychain_p.h
SOURCES += keychain.cpp

macx:SOURCES += keychain_mac.cpp
win32:SOURCES += keychain_win.cpp

